# Generated by Django 3.0.3 on 2020-04-13 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelID', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AmazonPriceTable',
            fields=[
                ('graphicscard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.GraphicsCard')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('timestamp', models.DateTimeField()),
                ('availability', models.BooleanField()),
                ('url', models.URLField(max_length=300)),
            ],
            bases=('backend.graphicscard',),
        ),
    ]
