# Generated by Django 3.0.3 on 2020-04-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphicscard',
            name='id',
        ),
        migrations.AlterField(
            model_name='graphicscard',
            name='model_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
