# Generated by Django 3.0.3 on 2020-04-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200416_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicscard',
            name='bus_size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='gpu_speed',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='manufacturer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='memory_bandwidth',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='graphicscard',
            name='memory_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
